logo_url: 'public/favicon.svg'

backend:
  name: github
  branch: master # change this to your branch
  repo: Edwinrj/lab-wpi-ece3849 # change this to your repo
  site_domain: ece3849.wpiembedded.com # change this to your domain
  base_url: https://ece3849.wpiembedded.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  # Labs
  - name: "labs"
    label: "Labs"
    label_singular: "Lab"
    folder: "src/content/docs/labs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  # Resources
  - name: "resources"
    label: "Resources"
    label_singular: "Resource"
    folder: "src/content/docs/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  # FAQ
  - name: "faq"
    label: "FAQ"
    label_singular: "Question"
    folder: "src/content/docs/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  # General Pages
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }